name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO: pipeittodevnull
  IMAGE: windbgx

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        context: git
        images: ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}
        flavor: latest=auto
        tags: |
          type=sha,enable=true,priority=100,prefix=,suffix=,format=long
          type=raw,value=devel,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile